# Generated by Django 4.2.2 on 2023-08-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_basemodel_remove_users_id_users_basemodel_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, default='user/default_img.png', upload_to='my_picture'),
        ),
    ]
